### PR TITLE
🌲 update prettier to the latest version 

### PR DESCRIPTION
**Pull request by fson**
The Sublime Text integration of Prettier doesn't work with older versions than 1.16.x anymore and I rely on it to format the code for me when editing files.

### CODE REVIEW

**Comment by cinderblock** [comment]
Why did this also update a bunch of code? Did prettier config change? Or did prettier defaults change?

**Comment by ericvicenti** [comment]
Different prettier versions often result in different printing. I'm going to try and rebase this and merge.. my VSCode extension has been conflicting with `yarn format` and the test, which slows me down because I need to format before committing 🤦‍♂️

**Comment by fson** [comment]
I've rebased and reformatted this now.

**Comment by fson** [comment]
Rebased again.

**Comment by fson** [comment]
Bumped it again to 1.17.0 and formatted all the code after that.

**Comment by fson** [comment]
Rebased again and renamed to match the commit naming convention 😄

**Comment by ericvicenti** [comment]
Looking great. For months I've been dealing with a conflicting prettier config vs eslint-prettier config, which is why I've avoided this. Managed to get it sorted out this time!

**Pull request merged**
